# frozen_string_literal: true

source "https://rubygems.org"

gem 'slack-ruby-bot'
gem 'puma'
gem 'sinatra'
gem 'dotenv'
gem 'celluloid-io'
gem 'sequel', '~> 5.6'
gem 'pg', '~> 1.0'
gem 'haml', '~> 5.0', '>= 5.0.4'

group :development, :test do
  gem 'rake'
  gem 'foreman'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'rubocop', '~> 0.52.1'
  gem 'rubocop-rspec', '~> 1.23'
  gem 'vcr'
  gem 'webmock'
end
