return { [[
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggtgggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggtgggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
gggggggggggggggggggggggggggggggg
]] }
